##################################
#         Global settings        #
##################################
listen_addresses = ['127.0.0.1:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true
force_tcp = true
timeout = 2500
log_level = 0
log_file = 'dnscrypt-proxy.log'
use_syslog = false
cert_refresh_delay = 240
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = false

#########################
#        Filters        #
#########################
block_ipv6 = true

##################################################################################
#        Route queries for specific domains to a dedicated set of servers        #
##################################################################################
forwarding_rules = 'dnscrypt-forwarding-rules.txt'

###############################
#        Cloaking rules       #
###############################
cloaking_rules = 'dnscrypt-cloaking-rules.txt'

###########################
#        DNS cache        #
###########################
cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

###############################
#        Query logging        #
###############################
[query_log]
  file = 'dnscrypt-query.log'
  format = 'tsv'

############################################
#        Suspicious queries logging        #
############################################
[nx_log]
  file = 'dnscrypt-nxdomain.log'
  format = 'tsv'

######################################################
#        Pattern-based blocking (blacklists)         #
######################################################
[blacklist]
  blacklist_file = 'dnscrypt-blacklist-domains.txt'
  log_file = 'dnscrypt-blacklist-domains.log'
  log_format = 'tsv'

###########################################################
#        Pattern-based IP blocking (IP blacklists)        #
###########################################################
[ip_blacklist]
  blacklist_file = 'dnscrypt-blacklist-ips.txt'
  log_file = 'dnscrypt-blacklist-ips.log'
  log_format = 'tsv'

#########################
#        Servers        #
#########################
[static]
  [static.'cisco']
  stamp = 'sdns://AQAAAAAAAAAADjIwOC42Ny4yMjAuMjIwILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ'
